language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm run-script build
deploy:
  provider: npm
  skip_cleanup: true
  email: fra.pirrotta@gmail.com
  api_key:
    secure: E7+sTULPowXQnlyTK/tIg4OEs3QbW3LJ/SekUbL8o2g9PcLznqPlWzRHEAsLDEv2pYibJ6tfIGgVHSmf0PJzIVFEMjC5OYbvFYjTI3nPI025/+oLyBMJCgOmfMm5altHGU7j+4wedaeHWZqbfG/iSyQOiX4om05lcnLQmUIV0fpEkV78ZD8dGTpveumUgiEWEclczs+7Mkc0ecHD09qR1rnyHT+qRy3I46XyrEcXLMtmLnw0XXUL+FN5ico56SXO8Y7cOv0FeyZkLVa7XLVGJGv++j61/0yMBVon8u1mww24xIl9jvsSCG+xEaJXwXztzPFaVYgLpJQXiE+B1cUqEsUmw1gR33TNG9vDb6xSwhOAMpqulcFO0jNYVxlt55cfr1rBVKdEFhMJBW63+ufOTF44NHb/5ZuersjanyAHCT1yof3ZRwrefl7drUkq2Ic5Ec87SVdZMTqUTYTnWv4nuWBD4cuFVtwQ83gfA5hn8O/lvnIxXkkYZ0iRXI6AVTwyLrt+JyyYJ/DkiZ1GK6l95biGgA8ZfQKPLjv6epOAiWnBALX8Usfmw1scifwTMv48NgtjXhrGPzeRHjku9HNftV63epGpachNdY9a6c3FEdgGanRLHOBHV1ymcsvgUuDhejElAn8CwS0a6khkAdtDlQCPWSLnJD5pWCSe5XVgbAQ=
  on:
    tags: true
    repo: pirropirro/signs-js
