language: node_js
node_js:
  - '6'
script:
  - npm run-script build
deploy:
  provider: npm
  email: "fra.pirrotta@gmail.com"
  api_key:
    secure: cmUCzTv3rI7oIAwTz9ZFUvhL+hxM7AmuRBJvQ6s9GCIkZm1a8KwB892uptNV2Po6gBRwuPuyUh8LRQfvegWzJTC3olJGTultqkr6nYIHMucEzpFkHeRXdWkITcpDpAAmXjFL3QnP3QY58GgZDoFsiCS2SRtOuWKCn6r0PA5biXs0NyxHIrODyNj/YITgwpmXbz6mAg1hOUdVdXmBjid9+AkVhLy8JPWU/bXuz0TETw+kzuyO/sKMR/3GP+v2yXFfC5LHidqYL7oPfqMwLmOBqmDmAAEpAD+Czw1+IbSXUvUUozIZu2uJyBugYLFvaE17Xm/8z86RnkG++AUM/qyJwViwl9kAZ/kVceFXfKSCbBD+yf7rpdRvSwz83/nJ3GAPa7oAb30XmQFvtDfOu/mfRplOi/wAZCMJqWcExJ0M9MOO1kvU0qSc3/GsLls9SpXJUfly32DMGCfalHP1YGpQrfKAAG5y3vKxKP0xiBxWiHEGEvEvEJXvNoIqfvYjLSLvXzV3lDcLjc/I91ME6rqb/bIcwCEXBLXl8X3ELmHK36R8xT+U9qHFbniGLtE4xC7CjJVe7PaW+EoMjVzh1yLhyPJHRKSag1l7L8e2jgoZb3Uj33JH9qFe7fG8NHE/P3YIuHveQvm3oqHlSOi/IEkZp7z8RpSrZEtLhIbvX2prBmY=