language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm run-script build
deploy:
  provider: npm
  skip_cleanup: true
  email: fra.pirrotta@gmail.com
  api_key:
    secure: 1xuQfqWy2Vhe1wegIJ9Pke6BaMmVLlGIgg5e6NjoZwh6h6f3y0H8g2eBD9x5sXbWPeCSL722DyyMLccPA/wBNtFry3D0PJ0oQ13yhMM8wDcRpnuK6MZ7sRjKxiic0lU/fP2FGQyJghnfazqzU8v5Z3BbFd3akZFWAAV6uuO3eGHqP3gsIyLozXA+PZLMJ0f0WXlOrMFHBwurkl3Wc6VwfrYQERPeiMCfRB4Vo48WJwnlC+6Yihgr05+ZhPsuUF/wKVzYEHtZN9any+rTKO49erDOfUtKywK4jVXcZWXMrxioYRQHD6jWzV7M1OcwyebTkTwgKH7f02xilfXzYI34oeAF7g5BIB34nACRgJPdCscgSuZx639DYaG6Ow7IeHTHj/ZL0kVArWl8cpwCuA7/TR1UyvnTCC4WRXCvV/ntQPR+afkW1rt9xdvhNiAGX4rJYxJ8a8T2+h6UDWkPB/tl4Uz8yZ2HL7JEQyo4CATThJgHDf3kjjrxwHCiJ99zwMZRsULn4ywMNJME1CAFqdl0VPEMiVx4boA77upiS7VM4D/l5iiDFOwfqh7/m57gelwnQ2kgo5PgV+wf/UfzNjrHo6dLw27z97tgJ9eYPeOgr8Ux4tSqsRFragw9+Aro/plbyNaPFV6X3A9Xoi4anwXHMQSgWUavQdkOsC5c4FsOqoA=
  on:
    tags: true