language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm run-script build
deploy:
  provider: npm
  skip_cleanup: true
  email: fra.pirrotta@gmail.com
  api_key:
    secure: "KIb7XVAF40cd9xL9wzbk8eTF1r/MgdxZ6BDSaYLPVkaOQb7P1nVekLzO9juygdaWpO0b/fWffWKJRa2XJRianBVpWwM3Rt0oEvuFRzKIlX9rIcoGHw6e4sxxmJPnrX8TtwFNZlaBplyknQw41RVkLNjTrSP+0++yP2wWWS9SMQvrm/04T4EiSAb7lTweAFjcpKIX9EVUgj9D0uMaAkcUs+fuQfYwOau0lLCA2fKEB8YomfrSuhtn3UUGcVk8Bkd94augti2lG4AjJDDpZI0RMyP25mBLTwt+tqpydHR4O7r0/d9Nn9+lXghpoxTbspbxzhS/OzOJHjdtwSToWxJZ8WbL7W7RJAQviSTWvgnUIrRgw6NWFcYlp9ZiI3qAx7Kj/7gtHhXHjBq9rFkBWmNZATUthOQ9GNyjbiSz2UF/FeFcluSONik/5kpcISxb4gvK1Lf/PD50QIzKT069Vk7N5AssWf2EhT3gLk8adn8PclswHdI1po+RuyvWus7lLQy+bO8VYp6ECGU6uhgDjMsgCczogna0qOw60mI51NpNn2wEcouRg8kvraSVAYOiXTHS+C1W9NhYoBuXejABo4AXYJ9kvrfefzYBTuHtg5oGv1/fygp6OfR3oRxbKRXV5AP9m68EJXKjOhD1vPoM9l1TRMVzwEUpBMVfRUWdxYC3tgs="
  on:
    tags: true